# Generated by Django 4.1.7 on 2023-02-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
